apiVersion: v1
kind: Pod
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  dnsConfig:
    options:
    - name: use-vc
  volumes:
  - name: config-volume
    configMap:
      name: envoy
  containers:
  - name: ubuntu
    image: threecomma/baseos:latest
    securityContext:
      privileged: true
    command:
    - sleep
    - "1000000"
  - name: envoy
    image: envoyproxy/envoy:v1.10.0
    volumeMounts:
    - name: config-volume
      mountPath: /etc/envoy
    args:
    - "-l"
    - "debug"
    - "-c"
    - "/etc/envoy/envoy.yaml"